# Generated by Django 6.1.1 on 2026-09-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Omborda qancha dona qolgani'),
        ),
    ]
