# Generated by Django 6.1.1 on 2026-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
