# Generated by Django 6.1.1 on 2026-09-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='phone_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
