# Generated by Django 6.1.1 on 2026-09-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Tasdiqlangan buyurtma',
                'verbose_name_plural': 'Tasdiqlangan buyurtmalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ShippedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Yuborilgan buyurtma',
                'verbose_name_plural': 'Yuborilgan buyurtmalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
