# Generated by Django 6.1.1 on 2026-09-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_confirmedorder_shippedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmedOrder',
        ),
        migrations.DeleteModel(
            name='ShippedOrder',
        ),
    ]
